spring:
  application:
    name: was
  jpa:
    open-in-view: false # osiv
    hibernate:
      ddl-auto: create # or update, create-drop, validate
    properties:
      hibernate:
        #        show_sql: true # system.out
        format_sql: true
  #        use_sql_comments: true
  h2:
    console:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug # logger
    org.hibernate.type: trace
---
spring:
  profiles:
    active: dev
  application:
    name: was
  jpa:
    #    database: h2
    open-in-view: false # osiv
    hibernate:
      ddl-auto: create # or update, create-drop, validate
    properties:
      hibernate:
        #        show_sql: true # system.out
        format_sql: true
  #        use_sql_comments: true

  datasource:
    url: jdbc:h2:mem:test

logging:
  level:
    org.hibernate.SQL: debug # logger
    org.hibernate.type: trace