spring:
  config:
    activate:
      on-profile: default
  application:
    name: was
  jpa:
    open-in-view: false # osiv
    hibernate:
      #      ddl-auto: create # or update, create-drop, validate
      ddl-auto: update # or update, create-drop, validate
    properties:
      hibernate:
        #        show_sql: true # system.out
        format_sql: true
    #        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://database-1.cxaay0sy093x.ap-northeast-2.rds.amazonaws.com/postgres
    username: postgres
    password: 4DklThlrLTdzNWP0J0T5
logging:
  level:
    org.hibernate.SQL: debug # logger
    org.hibernate.type: trace
  file:
    name: myapp.log
  logback:
    rollingpolicy:
      file-name-pattern: myapp.%d{yyyy-MM-dd}-%i.log
      max-file-size: 10KB
  pattern:
    dateformat: Asia/Seoul
cookie:
  max-age: 86400
jwtToken:
  accessToken:
    expiration: 10000
  refreshToken:
    expiration: 86400000
cors:
  allowed-origins: "https://woowangjwawang.vercel.app"
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: was
  jpa:
    #    database: h2
    open-in-view: false # osiv
    hibernate:
      ddl-auto: update # or update, create-drop, validate
    properties:
      hibernate:
        #        show_sql: true # system.out
        format_sql: true
  #        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: student
    password: 1234
  rsocket:
    server:
      mapping-path: "/rsocket"
      transport: "websocket"
logging:
  level:
    org.hibernate.SQL: debug # logger
    org.hibernate.type: trace
cookie:
  max-age: 86400
jwtToken:
  accessToken:
    expiration: 10000
  refreshToken:
    expiration: 86400000
cors:
  allowed-origins: "http://localhost:3000"