spring:
  application:
    name: was

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password: 1234
  
  jpa:
    database: mysql
    open-in-view: false # osiv ??. ?????? ???? ???? ??? ???? ????. entity? ????? ??(???? ??? ??) ?? ??
    hibernate:
      ddl-auto: create # or update, create-drop, validate
    properties:
      hibernate:
        #        show_sql: true # system.out ??
        format_sql: true
#        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug # logger? sql ??
    org.hibernate.type: trace
